import {Nunito, Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "../styles/globals.css";
import Header from '../components/Header'
import Footer from '../components/Footer'
import Providers from "./providers";
const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // add weights you need
});

// const nunito = Nunito({
//   variable: "--font-nunito",
//   subsets: ["latin"],
// });
export const metadata = {
  title: "",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
               <meta name="robots" content="noindex, nofollow" />
      </head>
      <body className={`bg-light ${nunito.className}`}>
     
      {/* <body> */}

       <Providers>
           <Header />
          {children}
                  <Footer />
        </Providers>

      </body>
    </html>
  );
}
