import {Nunito, Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "../styles/globals.css";
import Header from '../components/Header'
import Footer from '../components/Footer'
import Providers from "./providers";
import { headers } from "next/headers";
import Script from "next/script";
const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // add weights you need
});

export const metadata = {
  title: "",
  // description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
   const pathname = headers().get("x-invoke-path") || ""; // works in Next.js 14+
  const isAdmin = pathname.includes("admin");
    const lang = params?.country ; // fallback
    const countryCode = params?.country ; // fallback

  return (
    <html lang={lang}>
      <head>
               <meta name="robots" content="noindex, nofollow" />
               {/* External script */}
        {/* <Script src="https://example.com/custom.js" strategy="afterInteractive" /> */}
 {/* Inline script */}
        <Script id="custom-inline-script" strategy="afterInteractive">
          {`
            console.log("Custom JS loaded");
            document.body.classList.add("custom-loaded");
          `}
        </Script>
      </head>
      <body className={isAdmin ? `admin-body bg-light ${nunito.className}` : `bg-light ${nunito.className}`} >
     
      {/* <body> */}

       <Providers>
           <Header countryCode={countryCode} />
          {children}
                  <Footer />
        </Providers>

      </body>
    </html>
  );
}
